### PR TITLE
Rename subtree to subgraph

### PR DESCRIPTION
**Pull request by mikevoronov**
Intially, a fold instruction was designed based on idea that its iterable can't expand,
so AIR was considered as a subtree. But after introducing recursive streams in #225, it's
no more a subtree, but a subgraph.

### CODE REVIEW

**Comment by monoid** [comment]
Is it a generic graph, or something like a DAG?

**Comment by mikevoronov** [comment]
> Is it a generic graph, or something like a DAG?

It's a generic one because of recursive streams could be considered as a cycle.

**Comment by ValeryAntopol** [comment]
I think that it is also directed, and there exists a node that all other nodes are reachable from it.

**Comment by mikevoronov** [comment]
> I think that it is also directed, and there exists a node that all other nodes are reachable from it.

More precisely, it's a directed rooted graph.

**Review by ValeryAntopol — APPROVED** [review]
utACK

**Pull request merged**
